"""`eval.axis_check` -- the estimator that decides which gyro column is the vehicle's yaw axis.

Data-free: the axis is *planted* here and the estimator has to find it, so a failure means the
estimator is wrong rather than that the dataset changed. The measurement it makes on real bytes
is in DECISION_LOG D-095 and regenerated by `python -m eval.axis_check`.
"""

from __future__ import annotations

import numpy as np
import pytest

from eval.axis_check import GYRO_COLUMNS, regress_heading_on_integrated_gyro


def test_the_planted_yaw_axis_regresses_at_unit_slope_and_the_others_do_not():
    """Heading change and integrated yaw rate are the same angle, so the slope is exactly 1.

    That is the property the whole measurement rests on: there is no scale factor to fit, so a
    slope near 1 with a high R^2 identifies the axis and a slope of any other size does not.
    """
    rng = np.random.default_rng(26168)
    n = 400
    turned = rng.normal(0.0, 0.5, n)  # radians of heading change per block
    d_gyro = np.column_stack(
        [rng.normal(0.0, 0.5, n), turned, rng.normal(0.0, 0.5, n)]
    )

    slope, r2 = regress_heading_on_integrated_gyro(turned, d_gyro)

    assert GYRO_COLUMNS[int(np.argmax(r2))] == "gyro_pitch"
    assert slope[1] == pytest.approx(1.0, abs=1e-12)
    assert r2[1] == pytest.approx(1.0, abs=1e-12)
    for c in (0, 2):
        assert abs(r2[c]) < 0.05, f"column {c} should carry no heading information"


def test_the_sign_of_the_axis_is_reported_and_not_absorbed():
    """A column carrying the negated yaw rate fits at slope -1, not +1.

    The sign is the whole finding on IO-VNBD, so an estimator that returned |slope| would hide
    exactly the thing worth knowing.
    """
    rng = np.random.default_rng(94)
    turned = rng.normal(0.0, 0.4, 300)
    d_gyro = np.column_stack([rng.normal(0.0, 0.4, 300), -turned, rng.normal(0.0, 0.4, 300)])

    slope, r2 = regress_heading_on_integrated_gyro(turned, d_gyro)

    assert slope[1] == pytest.approx(-1.0, abs=1e-12)
    assert r2[1] == pytest.approx(1.0, abs=1e-12)


def test_a_noisy_axis_still_wins_but_its_r2_says_how_much_to_believe_it():
    """Regression dilution is why the real 1 Hz-GNSS stems fit at |slope| < 1.

    Noise in the *regressor* -- vibration on the gyro channel, or a course over ground differenced
    at 1 Hz -- attenuates the slope toward zero while leaving the axis identifiable. The estimator
    must keep reporting both numbers so a weak fit is visible as a weak fit.
    """
    rng = np.random.default_rng(47)
    turned = rng.normal(0.0, 0.5, 2000)
    noisy = turned + rng.normal(0.0, 0.5, 2000)
    d_gyro = np.column_stack([rng.normal(0.0, 0.5, 2000), noisy, rng.normal(0.0, 0.5, 2000)])

    slope, r2 = regress_heading_on_integrated_gyro(turned, d_gyro)

    assert GYRO_COLUMNS[int(np.argmax(r2))] == "gyro_pitch"
    assert 0.3 < slope[1] < 0.7, "an equal-variance regressor noise halves the slope"
    assert 0.3 < r2[1] < 0.7


def test_mismatched_shapes_are_refused_rather_than_broadcast():
    with pytest.raises(ValueError, match="same blocks"):
        regress_heading_on_integrated_gyro(np.zeros(5), np.zeros((6, 3)))
    with pytest.raises(ValueError, match=r"expected \(n, 3\)"):
        regress_heading_on_integrated_gyro(np.zeros(5), np.zeros((5, 2)))
